name: AldarEconomy
version: 0.0.1
author: dja12123@naver.com
description: 알다르 경제 시스템
main: kr.dja.aldarEconomy.AldarEconomy
commands:
    money:
        description: show player money
        usage: /money [player]
    moneydetail:
        description: show player money detail
        usage: /moneydetail [player]