name: AldarEconomy
version: 0.0.1
author: dja12123@naver.com
description: 알다르 경제 시스템
main: kr.dja.aldarEconomy.AldarEconomy
commands:
    money:
        description: show player money
        usage: /money [player]
    moneydetail:
        description: show player money detail
        usage: /moneydetail [player]
    moneyissuance:
        description: increase target player money
        usage: /moneyissuance <amount> [player]
    moneyconsume:
        description: decrease target player money
        usage: /moneyconsume <amount> [player]
    moneychestissuance:
        description: increase target chest money
        usage: /moneychestissuance <amount>
    moneychestconsume:
        description: decrease target chest money
        usage: /moneychestconsume <amount>
    moneyitemissuance:
        description: create moneyitem on target
        usage: /moneyitemissuance <amount>
    moneyp2c:
        description: move player money to target chest
        usage: /moneyp2c <amount> [player]
    moneyc2p:
        description: move target chest money to player
        usage: /moneyc2p <amount> [player]
    moneyp2p:
        description: move target player money to player
        usage: /moneyc2p <amount> <target> [source>]